name = "synpixel/fusion_jecs"
version = "0.1.0"
description = "A library which bridges the gap between your ECS and your UI"
authors = ["synpixel"]
repository = "https://github.com/synpixel/fusion-jecs"
license = "MIT"

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
